const translations = {
    ja: {
        "title": "ログイン & 初期登録 - MYアルバム アーティスト",
        "app_title_for_artists": "FOR ARTISTS",
        "invited_artist": "招待されたアーティスト",
        "artist_name_suffix": " 様",
        "invite_period": "有効期限: 発行日から90日以内 (2026/06/19まで)",
        "login_signup": "ログイン / 新規登録",
        "login_google": "Googleでログイン",
        "login_facebook": "Meta (Facebook) でログイン",
        "login_instagram": "Meta (Instagram) でログイン",
        
        "step1_title": "基本情報の登録",
        "step1_desc": "アーティスト活動に使用する情報を入力してください。",
        "label_name": "氏名",
        "label_phone": "電話番号",
        "label_email": "Email",
        "label_zip": "郵便番号",
        "label_address": "住所",
        "tag_required": "必須",
        "tag_optional": "任意",
        "placeholder_last_name": "氏 (例：蒼)",
        "placeholder_first_name": "名 (例：くみ)",
        "note_10chars": "※各10文字以内",
        "placeholder_phone": "例：09000000000",
        "note_no_hyphen": "※ハイフンなし",
        "placeholder_zip": "例：1500001",
        "placeholder_address": "例：東京都渋谷区...",
        "note_100chars": "※全角半角合計100文字以内",
        "btn_next": "次へ進む",
        "btn_back": "戻る",
        "error_10chars": "10文字以内で入力してください。",
        "error_11digits": "11桁以内の数値で入力してください。",
        "error_numeric": "数値のみで入力してください。",
        "error_email": "有効なメールアドレス（@を含む）を入力してください。",
        "error_7digits": "7桁の数値で入力してください。",
        "error_100chars": "100文字以内で入力してください。",
        
        "step2_title": "アルバムの設定",
        "step2_desc": "ファンが目にするアルバムの名前を設定します。",
        "label_album_name": "MYアルバム名",
        "placeholder_album_name": "例：蒼くみ推し活HUB",
        "note_change_later": "※後からマイページで変更可能です。",
        "note_20chars": "※20文字以内",
        "error_20chars": "20文字以内で入力してください。",

        "step3_title": "アイコン画像の登録",
        "step3_desc": "キュレーターアプリで表示されるアイコンです。",
        "icon_rec_title": "📸 アイコン画像の推奨設定",
        "icon_rec_1": "・推奨サイズ: 320×320px 以上の正方形 (1:1)",
        "icon_rec_2": "・ファイル容量: 8MB以内 (JPGまたはPNG)",
        "icon_rec_note": "※Instagramプロフィールの最適基準に合わせています",

        "step4_title": "事務所・マネージャー連絡先",
        "step4_desc": "運営からのお知らせを送付する連絡先を登録できます。",
        "step4_skip_title": "💡 この項目はスキップ可能です",
        "step4_skip_desc": "フリーランスの方や、後で登録されたい方は、何も入力せずに一番下の「スキップして完了する」を押すだけで初期登録がすべて完了します！",
        "label_office_name": "事務所名",
        "placeholder_office_name": "例：〇〇エンターテインメント",
        "note_50chars": "※全角半角50文字以内",
        "error_50chars": "50文字以内で入力してください。",
        "label_mgr_name": "担当マネージャー名",
        "placeholder_mgr_last": "氏 (例：佐藤)",
        "placeholder_mgr_first": "名 (例：太郎)",
        "label_mgr_phone": "担当者電話番号",
        "label_mgr_email": "担当者メールアドレス",
        "btn_skip_next": "入力をスキップして次へ進む",
        "btn_proceed_input": "入力内容で次へ進む",

        "step5_title": "利用プランのご選択",
        "step5_desc": "MYアルバムを快適にご利用いただくためのプランを選択してください。",
        "plan_basic": "ベーシック",
        "plan_standard": "スタンダード",
        "plan_premium": "プレミアム",
        "plan_month": " / 月",
        "plan_basic_desc": "年間データ転送量上限: 0.5TB",
        "plan_standard_desc": "年間データ転送量上限: 1TB",
        "plan_premium_desc": "年間データ転送量上限: 2TB",
        "plan_rec": "おすすめ",
        "plan_notice_title": "💡 データ転送量についての大切なお知らせ",
        "plan_notice_1": "データ転送料とは、アルバムへのアップロードやファンによるコンテンツ視聴等で発生する通信量（上り・下りのデータ送信量）です。",
        "plan_notice_2": "万が一、年間の転送量上限を超過した場合でも、オプションで追加チャージが可能です。",
        "plan_notice_3": "上限超過後に追加購入を行わなくても、<strong>1年間は大切なデータを安全に保持</strong>します（期間中のデータ引き出しも適宜可能です）。",
        "plan_notice_4": "※ 超過後、1年間一度も追加チャージ等が行われず放置された場合、データは消滅しますのであらかじめご注意ください。",
        "btn_confirm_plan": "プランを決定して次へ",

        "step6_title": "決済情報のご入力",
        "step6_desc": "選択したプランの決済情報を登録してください。",
        "selected_plan_suffix": "プラン",
        "selected_plan_desc_prefix": "データ転送上限: ",
        "selected_plan_desc_suffix": " / 年",
        "plan_cancel_note": "※ いつでも解約可能です",
        "stripe_error_title": "決済に失敗しました",
        "stripe_error_desc": "クレジットカード情報をご確認ください。どうしても解決しない場合は一旦ダッシュボードへ進み、後ほどマイページからご登録いただけます。",
        "btn_stripe_dashboard": "後で決済情報を登録してダッシュボードへ進む",
        "btn_stripe_open": "クレジットカード画面を開く",
        "stripe_safe_note": "※ Stripeの安全な決済ページへ遷移します",

        "modal_cancel": "キャンセル",
        "modal_plan_prefix": "MYアルバム ",
        "modal_contact": "連絡先情報",
        "placeholder_email": "メールアドレス",
        "modal_card": "カード情報",
        "placeholder_card_num": "カード番号",
        "placeholder_mmyy": "MM / YY",
        "placeholder_cvc": "CVC",
        "modal_cardholder": "カード名義人",
        "placeholder_cardholder": "TARO YAMADA",
        "btn_stripe_pay": "定期購入を申し込む",
        "demo_note1": "※ これは外部決済ページ（モック）のデモ画面です",
        "demo_note2": "[デモ用: 決済失敗アクションをテストする]",
        "error_card_num": "正しいカード番号を入力してください",
        "btn_processing": "処理中...",

        "db_home": "ホーム",
        "db_artist_name": "蒼くみ",
        "stat_curators": "キュレータ数",
        "stat_archives": "アーカイブ数",
        "stat_posts": "投稿数",
        "stat_god_certs": "神認定数",
        "stat_likes": "いいね",
        "stat_tipping": "投げ銭",
        "stat_note": "※上記の数値は総合計で記載されています",
        "db_recent_fans": "最近追加のあなたファン",
        "db_sns_status": "SNS連携ステータス",
        "db_sns_manage": "管理",
        "sns_syncing": "同期中",
        "sns_linked": "連携済",
        "sns_unlinked": "未連携",
        "db_storage_status": "MYストレージ契約状況",
        "storage_active": "契約中",
        "storage_plan": "プラン: スタンダード",
        "storage_desc": "PC版 MYストレージ と連携して、高品質な大容量アーカイブをセキュアに受け取れます。",
        "storage_usage_title": "伝送量の利用状況",
        "storage_total": "伝送合計",
        "storage_per_year": " /年間(12か月)",
        "storage_remain": "残伝送量",
        "storage_deposited": "預け量",
        "storage_end_date": "終了日",
        "nav_home": "ホーム",
        "nav_post": "MY投稿",
        "nav_review": "レビュー",
        "nav_invite": "招待",
        "nav_mypage": "マイページ",
        "profile_no_archive": "まだアーカイブはありません",
        "profile_modal_title": "新しいファンの情報",
        "profile_date_prefix": "登録日: ",
        "profile_creator_name": "クリエイターネーム (表示名)",
        "profile_bio": "自己紹介",
        "profile_view_archives": "アーカイブ一覧を見る",
        "profile_archive_list": "MYアルバム アーカイブ一覧",
        "profile_close_archives": "アーカイブ一覧を閉じる",
        "profile_limited": "MYアルバム限定コンテンツ",
        "type_video": "🎥 動画",
        "type_image": "📸 画像",
        "v_fan_meeting": "ファンミーティング編集版",
        "v_color_correction": "カラーコレクション",
        "tipping_modal_title": "投げ銭ランキング トップ20",

        "up_title": "MYアルバム限定アップロード",
        "up_title_short": "MYアルバム限定アップロード",
        "up_dest": "追加先アーカイブ",
        "up_mandatory": "※必須",
        "up_opt1": "東京ライブ 神ファンサシーンまとめ(共有)",
        "up_opt2": "夏服生写真メイキング映像",
        "up_opt_new": "＋ 新規アーカイブを作成する",
        "up_new_arch_name": "新しいアーカイブ名を入力",
        "up_new_arch_limit": "半角全角文字 20文字以内",
        "up_new_arch_unset": "未設定の新規アーカイブ",
        "up_note_1": "写真・動画を一度に20件までアップロードできます。",
        "up_note_2": "アップロード中は、この画面を閉じずにお待ちください。",
        "up_note_3": "安全にアップロードするため、通信が安定した場所でご利用ください。",
        "up_btn_select": "写真・動画を選ぶ",
        "up_btn_sub": "※ 1回につき最大20件まで",
        "up_sel_dest": "追加先アーカイブ:",
        "up_prep": "アップロード準備完了",
        "up_counts": "0 / 3件完了",
        "up_counts_done": "件完了",
        "up_btn_start": "アップロード開始",
        "up_status_wait": "待機中",
        "up_status_done": "完了",
        "up_status_err": "通信エラー",
        "up_status_up": "アップロード中...",
        "up_status_err_btn": "通信エラーが発生しました - 再試行",
        "up_status_err_txt": "通信が不安定です (Wi-Fi環境を推奨)",
        "up_status_success": "アップロード完了！",
        "up_success_msg1": "アップロードに成功しました",
        "up_success_msg2": "正常にアーカイブへ追加されました。<br>処理が完了次第、ファンに通知が送信されます。",
        "up_btn_back_db": "ダッシュボードへ戻る",

        "rev_title": "コンテンツレビュー",
        "rev_tab_exclusive": "MYアルバム限定一覧",
        "rev_tab_approved": "承認済",
        "rev_tab_unapproved": "未承認",
        "rev_desc_exclusive": "あなたがアップロードしたMYアルバム限定コンテンツの一覧です。",
        "rev_desc_approved": "承認済みのコンテンツ一覧です。神認定されたものは特別に強調表示されます。",
        "rev_desc_unapproved": "ファンやクリエイターから投稿された新着コンテンツを審査します。",
        "rev_public": "公開中",
        "rev_last_update": "最終更新: ",
        "rev_content_manage": "コンテンツ管理",
        "rev_badge_god": "✨ 神認定",
        "rev_badge_approved": "承認",
        "rev_time_register": "登録: ",
        "rev_time_approve": "承認: ",
        "rev_btn_reject": "却下",
        "rev_btn_approve": "承認",
        "rev_lbl_curator": "キュレーター / 投稿者",
        "rev_badge_unconfirmed": "未確認",
        "rev_btn_close": "閉じる",
        "rev_msg_rejected": "このコンテンツは却下されました",

        "mp_title": "マイページ",
        "mp_owner": "蒼くみ Official HUB オーナー",
        "mp_acct_setting": "アカウント設定",
        "mp_basic_info": "👤 基本情報の編集",
        "mp_mgr_info": "🏢 事務所・マネージャー連絡先の編集",
        "mp_login_info": "🔐 ログイン情報の変更",
        "mp_lang_setting": "🌐 言語切替 / Language",
        "mp_sns_link": "SNS自動連携設定",
        "mp_sns_linked": "連携中",
        "mp_sns_unlinked": "未連携",
        "mp_sns_btn_link": "連携する",
        "mp_sns_url_unset": "URLを設定...",
        "mp_logout": "ログアウト",
        
        "mp_b_modal_title": "基本情報の編集",
        "mp_b_modal_desc": "アーティスト活動に使用する基本情報を編集します。",
        "mp_lbl_req": "必須",
        "mp_lbl_opt": "任意",
        "mp_b_name": "氏名",
        "mp_b_name_desc": "※各10文字以内",
        "mp_b_tel": "電話番号",
        "mp_b_tel_desc": "※ハイフンなし",
        "mp_b_email": "Email",
        "mp_b_zip": "郵便番号",
        "mp_b_zip_desc": "※ハイフンなし",
        "mp_b_addr": "住所",
        "mp_b_addr_desc": "※全角半角合計100文字以内",
        "mp_btn_save": "保存する",
        "mp_msg_save_success": "✨ 保存しました。",
        
        "mp_m_modal_title": "事務所・マネージャー連絡先",
        "mp_m_modal_desc": "運営からのお知らせなどを送付する任意連絡先です。",
        "mp_m_office": "事務所名",
        "mp_m_office_desc": "※全角半角50文字以内",
        "mp_m_mgr_name": "担当マネージャー名",
        "mp_m_mgr_name_desc": "※各10文字以内",
        "mp_m_mgr_tel": "担当者電話番号",
        "mp_m_mgr_tel_desc": "※ハイフンなし",
        "mp_m_mgr_email": "担当者メールアドレス",

        "mp_js_login_msg": "ログイン方法の設定へ",
        "mp_js_sns_prompt": "のURLまたはユーザーIDを入力してください：",
        "mp_js_err_10_chars": "10文字以内で入力してください。",
        "mp_js_err_11_nums": "11桁以内の数値で入力してください。",
        "mp_js_err_nums_only": "数値のみで入力してください。",
        "mp_js_err_email": "有効なメールアドレス（@を含む）を入力してください。",
        "mp_js_err_7_nums": "7桁の数値で入力してください。",
        "mp_js_err_100_chars": "100文字以内で入力してください。",
        "mp_js_err_50_chars": "50文字以内で入力してください。",

        "inv_title": "ファン招待 - MYアルバム アーティスト",
        "inv_header": "キュレーター招待",
        "inv_hub_name": "蒼くみ 公式HUB招待",
        "inv_scan_desc": "このQRコードをスキャンして公認登録",
        "inv_btn_save": "画像を保存",
        "inv_btn_copy": "URLをコピー",
        "inv_note": "※公認キュレーターは、あなたのオリジナル素材を<br>使用して二次創作コンテンツを作成できます。",
        "inv_msg_save": "QR画像を保存しました",
        "inv_msg_copy": "招待URLをコピーしました！",

        "vl_tokyo_title": "東京ライブ 神ファンサシーンまとめ - MYアルバム",
        "vl_badge_arch": "限定公開中",
        "vl_tokyo_h1": "東京ライブ 神ファンサシーンまとめ(共有)",
        "vl_tokyo_desc": "過去の東京ライブ配信から、神がかっているファンサ対応の瞬間だけを繋ぎ合わせた究極のまとめ集です。<br>合計22ファイルの動画・画像が収録されています。",
        
        "vl_stat_likes": "総いいね ❤️",
        "vl_stat_tips": "総投げ銭額 🎁",
        "vl_stat_views": "総閲覧数 👁",
        
        "vl_list_header": "コンテンツ別 統計",
        "vl_tokyo_count": "全 22 コンテンツ",
        "vl_badge_photo": "画像",
        "vl_as_likes": "獲得いいね",
        "vl_as_tips": "獲得投げ銭",

        "vl_summer_title": "夏服生写真メイキング映像 - MYアルバム",
        "vl_summer_h1": "夏服生写真メイキング映像",
        "vl_summer_desc": "夏服生写真撮影の裏側に密着した特別映像と未公開オフショットのまとめです。<br>合計20ファイルの動画・画像が収録されています。",
        "vl_summer_count": "全 20 コンテンツ",

        "vl_t_scene1": "登場シーン 歓喜の瞬間",
        "vl_t_scene2_tokyo": "メインビジュアル 全身ショット",
        "vl_t_scene3": "神MC 爆笑トーク集",
        "vl_t_scene4": "バックステージ オフショット",
        "vl_t_scene5": "カメラ目線の神ウインク",
        "vl_t_hl_tokyo": "ライブハイライトシーン ",
        
        "vl_t_scene2_summer": "夏服 特別衣装 全身ショット",
        "vl_t_hl_summer": "メイキングハイライトシーン "
    },
    en: {
        "title": "Login & Registration - MY Album Artist",
        "app_title_for_artists": "FOR ARTISTS",
        "invited_artist": "Invited Artist",
        "artist_name_suffix": "",
        "invite_period": "Valid: Within 90 days of issue (Until 2026/06/19)",
        "login_signup": "Login / Sign Up",
        "login_google": "Continue with Google",
        "login_facebook": "Continue with Meta (Facebook)",
        "login_instagram": "Continue with Meta (Instagram)",
        
        "step1_title": "Basic Information",
        "step1_desc": "Please enter your info for artist activities.",
        "label_name": "Name",
        "label_phone": "Phone Number",
        "label_email": "Email",
        "label_zip": "Zip Code",
        "label_address": "Address",
        "tag_required": "Required",
        "tag_optional": "Optional",
        "placeholder_last_name": "Last (e.g. Aoi)",
        "placeholder_first_name": "First (e.g. Kumi)",
        "note_10chars": "*Max 10 characters",
        "placeholder_phone": "e.g. 09000000000",
        "note_no_hyphen": "*No hyphens",
        "placeholder_zip": "e.g. 1500001",
        "placeholder_address": "e.g. Shibuya-ku, Tokyo...",
        "note_100chars": "*Max 100 characters combined",
        "btn_next": "Next",
        "btn_back": "Back",
        "error_10chars": "Please enter up to 10 characters.",
        "error_11digits": "Please enter up to 11 numeric digits.",
        "error_numeric": "Please enter numbers only.",
        "error_email": "Please enter a valid email address.",
        "error_7digits": "Please enter a 7-digit number.",
        "error_100chars": "Please enter up to 100 characters.",
        
        "step2_title": "Album Settings",
        "step2_desc": "Set the name of the album your fans will see.",
        "label_album_name": "MY Album Name",
        "placeholder_album_name": "e.g. Kumi Aoi Official HUB",
        "note_change_later": "*Can be changed later on My Page.",
        "note_20chars": "*Max 20 characters",
        "error_20chars": "Please enter up to 20 characters.",

        "step3_title": "Icon Image Registration",
        "step3_desc": "This icon will be displayed in the curator app.",
        "icon_rec_title": "📸 Recommended Icon Settings",
        "icon_rec_1": "• Recommended size: 320x320px or larger square (1:1)",
        "icon_rec_2": "• File size: Under 8MB (JPG or PNG)",
        "icon_rec_note": "*Optimized for Instagram profile standards",

        "step4_title": "Agency / Manager Contact",
        "step4_desc": "Register a contact to receive admin notifications.",
        "step4_skip_title": "💡 This section is optional",
        "step4_skip_desc": "Freelancers or those who wish to register later can complete registration by clicking 'Skip and Next' below!",
        "label_office_name": "Agency Name",
        "placeholder_office_name": "e.g. XX Entertainment",
        "note_50chars": "*Max 50 characters",
        "error_50chars": "Please enter up to 50 characters.",
        "label_mgr_name": "Manager Name",
        "placeholder_mgr_last": "Last (e.g. Sato)",
        "placeholder_mgr_first": "First (e.g. Taro)",
        "label_mgr_phone": "Manager Phone Number",
        "label_mgr_email": "Manager Email",
        "btn_skip_next": "Skip input and Next",
        "btn_proceed_input": "Proceed with entered details",

        "step5_title": "Select a Plan",
        "step5_desc": "Select a plan for comfortable use of MY Album.",
        "plan_basic": "Basic",
        "plan_standard": "Standard",
        "plan_premium": "Premium",
        "plan_month": " / mo",
        "plan_basic_desc": "Annual Data Transfer Limit: 0.5TB",
        "plan_standard_desc": "Annual Data Transfer Limit: 1TB",
        "plan_premium_desc": "Annual Data Transfer Limit: 2TB",
        "plan_rec": "Recommended",
        "plan_notice_title": "💡 Important Notice Regarding Data Transfer",
        "plan_notice_1": "Data transfer volume includes up/down traffic from album uploads and fan views.",
        "plan_notice_2": "If you exceed the annual limit, you can purchase additional data charges.",
        "plan_notice_3": "Even if you exceed the limit without adding charges, your data is <strong>safely kept for 1 year</strong>.",
        "plan_notice_4": "* Note that if left for a year without additional charges after exceeding the limit, data will be deleted.",
        "btn_confirm_plan": "Confirm Plan and Next",

        "step6_title": "Payment Information",
        "step6_desc": "Register payment info for your selected plan.",
        "selected_plan_suffix": " Plan",
        "selected_plan_desc_prefix": "Data Transfer Limit: ",
        "selected_plan_desc_suffix": " / yr",
        "plan_cancel_note": "* Can be canceled at any time",
        "stripe_error_title": "Payment Failed",
        "stripe_error_desc": "Check your credit card. If not resolved, proceed to dashboard and register later from My Page.",
        "btn_stripe_dashboard": "Register Payment Info Later and Proceed",
        "btn_stripe_open": "Open Credit Card Screen",
        "stripe_safe_note": "* Redirects to Stripe's secure payment page",

        "modal_cancel": "Cancel",
        "modal_plan_prefix": "MY Album ",
        "modal_contact": "Contact Information",
        "placeholder_email": "Email Address",
        "modal_card": "Card Information",
        "placeholder_card_num": "Card Number",
        "placeholder_mmyy": "MM / YY",
        "placeholder_cvc": "CVC",
        "modal_cardholder": "Cardholder Name",
        "placeholder_cardholder": "TARO YAMADA",
        "btn_stripe_pay": "Subscribe",
        "demo_note1": "* This is a demo of an external payment page (mock)",
        "demo_note2": "[Demo: Test Payment Failure Action]",
        "error_card_num": "Please enter a valid card number",
        "btn_processing": "Processing...",

        "db_home": "Home",
        "db_artist_name": "Kumi Aoi",
        "stat_curators": "Curators",
        "stat_archives": "Archives",
        "stat_posts": "Posts",
        "stat_god_certs": "God Certs",
        "stat_likes": "Likes",
        "stat_tipping": "Tipping",
        "stat_note": "* The above figures are totals",
        "db_recent_fans": "Recently Added Fans",
        "db_sns_status": "SNS Link Status",
        "db_sns_manage": "Manage",
        "sns_syncing": "Syncing",
        "sns_linked": "Linked",
        "sns_unlinked": "Unlinked",
        "db_storage_status": "MY Storage Status",
        "storage_active": "Active",
        "storage_plan": "Plan: Standard",
        "storage_desc": "Link with PC MY Storage to securely receive high-quality large archives.",
        "storage_usage_title": "Data Usage",
        "storage_total": "Total Data",
        "storage_per_year": " /Year (12 mos)",
        "storage_remain": "Remaining",
        "storage_deposited": "Deposited",
        "storage_end_date": "End Date",
        "nav_home": "Home",
        "nav_post": "MY Posts",
        "nav_review": "Review",
        "nav_invite": "Invite",
        "nav_mypage": "My Page",
        "profile_no_archive": "No archives yet",
        "profile_modal_title": "New Fan Information",
        "profile_date_prefix": "Registered: ",
        "profile_creator_name": "Creator Name (Display Name)",
        "profile_bio": "Bio",
        "profile_view_archives": "View Archives",
        "profile_archive_list": "MY Album Archives",
        "profile_close_archives": "Close Archives",
        "profile_limited": "MY Album Limited Content",
        "type_video": "🎥 Video",
        "type_image": "📸 Image",
        "v_fan_meeting": "Fan Meeting Edit",
        "v_color_correction": "Color Correction",
        "tipping_modal_title": "Tipping Ranking Top 20",

        "up_title": "MY Album Limited Upload",
        "up_title_short": "MY Album Limited Upload",
        "up_dest": "Destination Archive",
        "up_mandatory": "* Required",
        "up_opt1": "Tokyo Live Best Fan Service Compilation",
        "up_opt2": "Summer Outfit Photo Making Video",
        "up_opt_new": "+ Create New Archive",
        "up_new_arch_name": "Enter New Archive Name",
        "up_new_arch_limit": "Max 20 characters",
        "up_new_arch_unset": "Unset New Archive",
        "up_note_1": "Upload up to 20 photos/videos at once.",
        "up_note_2": "Please do not close this screen during upload.",
        "up_note_3": "Use a stable connection for safe uploading.",
        "up_btn_select": "Select Photos/Videos",
        "up_btn_sub": "* Max 20 items per upload",
        "up_sel_dest": "Destination:",
        "up_prep": "Upload Ready",
        "up_counts": "0 / 3 completed",
        "up_counts_done": " completed",
        "up_btn_start": "Start Upload",
        "up_status_wait": "Waiting",
        "up_status_done": "Done",
        "up_status_err": "Connection Error",
        "up_status_up": "Uploading...",
        "up_status_err_btn": "Connection Error - Retry",
        "up_status_err_txt": "Unstable connection (Wi-Fi recommended)",
        "up_status_success": "Upload Complete!",
        "up_success_msg1": "Upload successful",
        "up_success_msg2": "Successfully added to archive.<br>Notification will be sent to fans once processed.",
        "up_btn_back_db": "Return to Dashboard",

        "rev_title": "Content Review",
        "rev_tab_exclusive": "MY Album Limited",
        "rev_tab_approved": "Approved",
        "rev_tab_unapproved": "Unapproved",
        "rev_desc_exclusive": "List of MY Album limited content you have uploaded.",
        "rev_desc_approved": "List of approved content. God Certified items are highlighted.",
        "rev_desc_unapproved": "Review new content posted by fans and creators.",
        "rev_public": "Public",
        "rev_last_update": "Last Update: ",
        "rev_content_manage": "Manage Content",
        "rev_badge_god": "✨ God Certified",
        "rev_badge_approved": "Approved",
        "rev_time_register": "Reg: ",
        "rev_time_approve": "Appr: ",
        "rev_btn_reject": "Reject",
        "rev_btn_approve": "Approve",
        "rev_lbl_curator": "Curator / Poster",
        "rev_badge_unconfirmed": "Unconfirmed",
        "rev_btn_close": "Close",
        "rev_msg_rejected": "This content has been rejected",

        "mp_title": "My Page",
        "mp_owner": "Aoi Kumi Official HUB Owner",
        "mp_acct_setting": "Account Settings",
        "mp_basic_info": "👤 Edit Basic Info",
        "mp_mgr_info": "🏢 Edit Office/Manager Contact",
        "mp_login_info": "🔐 Change Login Info",
        "mp_lang_setting": "🌐 言語切替 / Language",
        "mp_sns_link": "SNS Auto-Link Settings",
        "mp_sns_linked": "Linked",
        "mp_sns_unlinked": "Not Linked",
        "mp_sns_btn_link": "Link",
        "mp_sns_url_unset": "Set URL...",
        "mp_logout": "Logout",
        
        "mp_b_modal_title": "Edit Basic Info",
        "mp_b_modal_desc": "Edit the basic information used for artist activities.",
        "mp_lbl_req": "Required",
        "mp_lbl_opt": "Optional",
        "mp_b_name": "Name",
        "mp_b_name_desc": "* Max 10 chars each",
        "mp_b_tel": "Phone Number",
        "mp_b_tel_desc": "* No hyphens",
        "mp_b_email": "Email",
        "mp_b_zip": "Zip Code",
        "mp_b_zip_desc": "* No hyphens",
        "mp_b_addr": "Address",
        "mp_b_addr_desc": "* Max 100 chars total",
        "mp_btn_save": "Save",
        "mp_msg_save_success": "✨ Saved.",
        
        "mp_m_modal_title": "Office/Manager Contact",
        "mp_m_modal_desc": "Optional contact for notifications from operations.",
        "mp_m_office": "Office Name",
        "mp_m_office_desc": "* Max 50 chars",
        "mp_m_mgr_name": "Manager Name",
        "mp_m_mgr_name_desc": "* Max 10 chars each",
        "mp_m_mgr_tel": "Manager Phone",
        "mp_m_mgr_tel_desc": "* No hyphens",
        "mp_m_mgr_email": "Manager Email",

        "mp_js_login_msg": "To Login settings",
        "mp_js_sns_prompt": " URL or User ID:",
        "mp_js_err_10_chars": "Max 10 characters.",
        "mp_js_err_11_nums": "Max 11 digits.",
        "mp_js_err_nums_only": "Numbers only.",
        "mp_js_err_email": "Enter a valid email (including @).",
        "mp_js_err_7_nums": "Expected 7 digits.",
        "mp_js_err_100_chars": "Max 100 characters.",
        "mp_js_err_50_chars": "Max 50 characters.",

        "inv_title": "Fan Invite - MY Album Artist",
        "inv_header": "Curator Invite",
        "inv_hub_name": "Aoi Kumi Official HUB Invite",
        "inv_scan_desc": "Scan this QR code to register officially",
        "inv_btn_save": "Save Image",
        "inv_btn_copy": "Copy URL",
        "inv_note": "* Official Curators can create secondary content<br>using your original materials.",
        "inv_msg_save": "QR image saved",
        "inv_msg_copy": "Invite URL copied to clipboard!",

        "vl_tokyo_title": "Tokyo Live Best Fan Service - MY Album",
        "vl_badge_arch": "Limited Release",
        "vl_tokyo_h1": "Tokyo Live Best Fan Service (Shared)",
        "vl_tokyo_desc": "The ultimate compilation piecing together only the god-tier moments of fan service from past Tokyo Live streams.<br>A total of 22 video and image files are included.",
        
        "vl_stat_likes": "Total Likes ❤️",
        "vl_stat_tips": "Total Tips 🎁",
        "vl_stat_views": "Total Views 👁",
        
        "vl_list_header": "Stats per Content",
        "vl_tokyo_count": "22 Contents in Total",
        "vl_badge_photo": "Photo",
        "vl_as_likes": "Likes Earned",
        "vl_as_tips": "Tips Earned",

        "vl_summer_title": "Summer Outfit Making-of - MY Album",
        "vl_summer_h1": "Summer Outfit Photoshoot Making-of",
        "vl_summer_desc": "A special compilation featuring behind-the-scenes footage and unreleased shots from the summer outfit photoshoot.<br>A total of 20 video and image files are included.",
        "vl_summer_count": "20 Contents in Total",

        "vl_t_scene1": "Entrance Scene - Moment of Joy",
        "vl_t_scene2_tokyo": "Main Visual - Full Body Shot",
        "vl_t_scene3": "God MC - Hilarious Talk Compilation",
        "vl_t_scene4": "Backstage Off-shots",
        "vl_t_scene5": "God-tier Wink to the Camera",
        "vl_t_hl_tokyo": "Live Highlight Scene ",
        
        "vl_t_scene2_summer": "Summer Outfit Special Costume - Full Body Shot",
        "vl_t_hl_summer": "Making-of Highlight Scene "
    }
};

let currentLang = localStorage.getItem('myAlbumLang') || 'ja';

function t(key) {
    return translations[currentLang][key] || key;
}

function updatePageLanguage() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang][key]) {
            if (el.tagName === 'INPUT' && el.hasAttribute('placeholder')) {
                el.placeholder = translations[currentLang][key];
            } else {
                // To keep inner HTML structure like span intact, for pure text elements we use textContent or innerHTML based on if it contains html tags.
                // Usually we just replace innerHTML.
                el.innerHTML = translations[currentLang][key];
            }
        }
    });
    
    // Update plan and billing specific texts dynamically if they are displayed
    if(typeof confirmPlan === 'function') {
        if (currentPlanPrice === 600) currentPlanName = t('plan_basic');
        if (currentPlanPrice === 900) currentPlanName = t('plan_standard');
        if (currentPlanPrice === 1500) currentPlanName = t('plan_premium');
        
        // Let confirmPlan handle the current dynamic values
        confirmPlan(); 
    }
    
    // Update button states
    const btnCompleteMgr = document.getElementById('btn-complete-mgr');
    if (btnCompleteMgr) {
        checkStep4(); // This triggers translation update based on input state
    }
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('myAlbumLang', lang);
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if (btn.dataset.lang === lang) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }
    });

    updatePageLanguage();
}

// Initialization for page load
document.addEventListener('DOMContentLoaded', () => {
    updatePageLanguage();
});
